### ISSUE TITLE
Client crash with liteloader installed

### ISSUE THREAD

**Issue by klangg** [specialattack/SpACoreForge#2]
When I have Forge 1.7.10-10.13.2.1291, SpACore-1.7.10-01.05.03.00, and liteloader-1.7.10-04 instilled on my client I get the following crash before hitting the main menu splashscreen: http://pastebin.com/13ZNaipx

I went to report on the LiteLoader thread as well and there was already a response to the same error posted previously: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290155-liteloader-for-minecraft-1-7-10?comment=4006

    Quote from Mumfrey»
    You have another mod installed with a bad transformer which is not checking for nulls. From your stack trace it looks like "Special Attack" something or other.

**Comment by heldplayer** [comment]
I've uploaded a fix to CurseForge, it should be available shortly.

**Comment by klangg** [comment]
That worked. Thanks for the great mods and the fast response.
